INSERT INTO stories (title, story, name, likes, userid) values ('The great escape', 'For the first time I felt like I could escape the uncertainty by getting stuck into a good book at home, it was so relieving', 'Joe', 0, 1);

INSERT INTO stories (title, story, name, likes, userid) values ('NZ Returns to Normal', 'New Zealand Prime Minister Jacinda Adern announced at the beginning of the week that all restrictions including social distancing would now be lifted and that the nation was free of Covid-19 after no new cases for a fortnight. The country borders remain closed.', 'Gemma', 1, 1);

INSERT INTO stories (title, story, name, likes, userid) values ('Coronavirus Cases Decline In The UK', 'The cases of Covid-19 in the UK have been steadily declining in the UK over the last few days, with the lowest death rate since lockdown began (55 people) announced on Tuesday. On Sunday and Monday, Northern Ireland and Scotland reported no new deaths as a result of the Coronavirus. Though it is important to note there is usually a reporting lag of numbers at the weekend - on Tuesday, the Scottish government said 7 people had died in the preceding 24 hours.', 'Tommy', 3, 1);

INSERT INTO stories (title, story, name, likes, userid) values ('London Coronavirus Cases Are Dwindling', 'Though the exact number of new cases of Covid-19 in London appear to have conflicted over the past few days, one thing that is sure is that right now they are much lower than they were a few weeks ago. According to the Mayor of London office, only 13 people tested positive for Covid-19 on Tuesday (May 20th). The Telegraph also report that six major London hospitals reported no new deaths from the virus in the past 48 hours.', 'Gerry', 4, 1);

INSERT INTO stories (title, story, name, likes, userid) values ('Airline Staff Support Healthcare Workers', 'A new initiative called Project Wingman, set up by two pilots and fronted by furloughed airline staff as volunteers, is providing NHS workers with a first class lounge experience between shifts. Staff can indulge in a nice cup of tea with handmade sandwiches. So far, there are 60 lounges open run by 4000 volunteers.', 'Melissa', 3, 1);

INSERT INTO stories (title, story, name, likes, userid) values ('Socially Distant Weddings', 'With many weddings put on hold due to the Coronavirus outbreak, other ways of ensuring people can still get married have been enacted around the world. In California, a pop-up socially distanced wedding service has been erected where only one witness is allowed. This wedding - held on May 19th - between Rodney and Monica Cosby was set up by the Orange County Clerk-Recorders in Anaheim at the Honda Centre, and was performed by a Clerk inside the pop up.', 'Dorothy', 2, 2);

INSERT INTO stories (title, story, name, likes, userid) values ('92-year-old Teaches Piano From Quarantine', '92-year-old Holocaust survivor Dr Cornelia Vertenstein is continuing to teach piano to students from her home in Denver. The music teacher has been delivering the lessons via FaceTime from her iPad', 'Samantha', 8, 2);

INSERT INTO stories (title, story, name, likes, userid) values ('International Nurses Day', 'Though the work of nurses is to be celebrated always, International Nurses Day (which was celebrated on May 13) took on added significance in light of the communities and their tireless work to care for patients during the Coronavirus pandemic. Many marked and celebrated the day including members of the royal family who spoke to nurses in the UK and across the Commonwealth to thank them for their service.', 'Tayla', 3, 2);

INSERT INTO stories (title, story, name, likes, userid) values ('Finding Love Through Social Distancing', 'The BBC reported how one couple found each other from across balconies while they stayed at home during the lockdown. If the whole balcony thing is feeling quite Romeo and Juliet to you, the whole event has actually unfurled in Verona, Italy - the city of the famous love story.
After noticing one another, they looked each other up on social media and have been messaging ever since. And, now, they cannot wait until their first real date in person.', 'Danielle', 3, 2);

INSERT INTO stories (title, story, name, likes, userid) values ('Countries Easing Restrictions', 'After successful periods of social distancing measures, some countries have started easing their lockdown restrictions. To kick off this week, New Zealand announced that there had been no more local transmissions of Covid-19, meaning some non-essential businesses, healthcare and education can resume after a month of strict lockdown. Many people are still required to stay at home. The picture above shows Kiwi pro surfing champion Ava Henderson returning to the sea. In Spain, children have been allowed outside for walks for the first time in weeks and in China some have returned to school.', 'Martha', 12, 2);

INSERT INTO stories (title, story, name, likes, userid) values ('Perfect Rainbow Appears In New York City', 'New York state is the worst hit area of the United States when it comes to the Coronavirus pandemic, with more than 100,000 confirmed cases. On Easter Monday, residents in the city were given something to smile about as a full rainbow appeared over the Hudson river.', 'Simon', 5, 2);

INSERT INTO stories (title, story, name, likes, userid) values ('The Himalayas Become Visible For First Time In Years', 'According to CNN, locals in the Punjab region of India have been able to see the Himalayas for the first time in decades due to reduced levels of pollution since India started the Covid-19 lockdown. Delhi is believed to have experienced a 44% reduction in air pollution levels in the first day or so of lockdown.', 'Sally', 4, 3);

INSERT INTO stories (title, story, name, likes, userid) values ('Husband Supports Wife Through Cancer Treatment Through Window', 'With the outbreak of Covid-19, the majority of hospitals have enforced no or reduced visitor rules for health and safety reasons. When this meant that he could not sit with his wife through her chemotherapy treatment for breast cancer in Texas, he held up a makeshift sign and positioned himself in her view through the window to support her, reports Good Morning America.', 'Albert', 10, 3);

INSERT INTO stories (title, story, name, likes, userid) values ('Doctors Wear Photos Of Themselves Smiling To Ease Patients', 'While medical staff across the world are wearing PPE (personal, protective equipment) such as masks and overalls to keep themselves safe as they treat patients with Covid-19, some have oped to put photos of themselves smiling, along with their name, to put worried patients at ease. This emergency doctor from San Diego, California shared his photo on Instagram, writing that his patients can now see a reassuring and comforting smile', 'Martino', 5, 3);

INSERT INTO stories (title, story, name, likes, userid) values ('Rainbow Drawings', 'If you have been out on a daily run or walk during lockdown, you may have noticed drawings of rainbows placed in the windows of homes. All over the UK, the drawings - which are intended to spread hope during this time, particularly to NHS and key workers - have been cropping up, including at this house in Bournemouth.', 'Vanessa', 4, 3);

-- USERS --

INSERT INTO stories (title, story, name, likes, userid) values ('Rainbow Drawings', 'If you have been out on a daily run or walk during lockdown, you may have noticed drawings of rainbows placed in the windows of homes. All over the UK, the drawings - which are intended to spread hope during this time, particularly to NHS and key workers - have been cropping up, including at this house in Bournemouth.', 'Vanessa', 4, 3);